# Generated by Django 3.2 on 2023-10-19 08:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None, unique=True, verbose_name='Цвет тега'),
        ),
    ]
